### ISSUE TITLE
Failed to load snippets: Duplicate key 'v-btn with raised prop'

### ISSUE THREAD

**Issue by matthanson12** [vuetifyjs/vuetify-atom#1]
Tried installing and I get this error. 

![image](https://user-images.githubusercontent.com/6919027/37737037-fc23249a-2d28-11e8-9445-ad48454ca775.png)

**Comment by berendsmatt** [comment]
Same error.
Wish the error showed where the duplicate key was located, can't find it anywhere.

**Comment by abhaywawale** [comment]
will look into it.

**Comment by abhaywawale** [comment]
Done.

**Comment by matthanson12** [comment]
New error now, Duplicate key 'hidden xs and up - Vuetify'
